version: '3.2'

services:
  database:
    image: postgres:12.6-alpine
    restart: always
    ports:
      - 5432
    environment:
      - POSTGRES_PASSWORD=turbo
      - POSTGRES_USER=turbo
      - POSTGRES_DB=turbo
    volumes:
      - postgres:/data

volumes:
  postgres: ~
